version: "3.0"
services:
  backend:
    container_name: foodfinder-backend
    image: mongo:latest
    restart: always
    environment:
      DB_NAME: foodfinder
      MONGO_INITDB_DATABASE: foodfinder
    ports: 
      - 27017:27017
    volumes:
      - "./.docker/foodfinder-backend/seed-mongodb.js:/docker-entrypoint-initdb.d/seed-mongodb.js"
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container

    

